server:
  port: 8091
spring:
  application:
    name: application
  cloud:
    config:
      uri: http://ms-config-server:8888
      failFast: true
      retry:
        initialInterval: 2000
        maxAttempts: 30
