
spring:
  application:
    name: product-command-side
  cloud:
    config:
      uri: http://ms-config-server:8888
      failFast: true
      retry:
        initialInterval: 2000
        maxAttempts: 30
